version: 2.1
description: |
  Will install dev and packaging extra dependencies from
  setup.py.

workflows:
  version: 2.1
  lint:
    jobs:
      - build
      - flake8:
          requires:
            - build
      - black:
          requires:
            - build
      - isort:
          requires:
            - build
      - mypy:
          requires:
            - build

executors:
  python:
    description: Python image build image
    parameters:
      version:
        description: Python version to use
        type: string
        default: "3.8"
    docker:
      - image: circleci/python:<<parameters.version>>
        environment:
          POETRY_VIRTUALENVS_PATH: /home/circleci/td-cli/.cache

references:
  container_config: &container_config
    working_directory: ~/td-cli
    executor:
      name: python
      version: <<parameters.python-version>>
    parameters:
      python-version:
        description: Python version to use
        type: string
        default: "3.8"
      cache-version:
        description: A cache version that may be used for cache busting
        type: string
        default: "v2"

commands:
  # Use a venv so we don't have to run as root to make caches work
  setup_venv_and_install_deps:
    description: |
      Setup a python venv for the project.
      Install project dependencies into a virtual environment.

      Installs the dependencies declared in pyproject.toml, including all
      dev dependencies.
    parameters:
      cache-version:
        description: A cache version that may be used for cache busting
        type: string
        default: "v2"
    steps:
      - restore_cache:
          key: <<parameters.cache-version>>-poetry-cache-{{ checksum "poetry.lock" }}
      - run: make requirements
      - save_cache:
          key: <<parameters.cache-version>>-poetry-cache-{{ checksum "poetry.lock" }}
          paths:
            - .cache

jobs:
  build:
    description: Build and install dependencies
    <<: *container_config
    steps:
      - checkout
      - setup_venv_and_install_deps:
          cache-version: <<parameters.cache-version>>
      - persist_to_workspace:
          root: ~/td-cli
          paths:
            - .cache
            - Makefile
            - todo
            - pyproject.toml
            - setup.cfg

  isort:
    description: Execute import order checks with isort
    <<: *container_config
    steps:
      - attach_workspace:
          at: ~/td-cli
      - run: make isort

  black:
    description: Execute code format checks with black
    <<: *container_config
    steps:
      - attach_workspace:
          at: ~/td-cli
      - run: make black

  flake8:
    description: Execute code format checks with flake8
    <<: *container_config
    steps:
      - attach_workspace:
          at: ~/td-cli
      - run: make flake8

  mypy:
    description: Execute code format checks with mypy
    <<: *container_config
    steps:
      - attach_workspace:
          at: ~/td-cli
      - run: make mypy
